<a href="https://colab.research.google.com/github/divya2212001/colabs/blob/main/Copy_of_Lecture_13_DVA.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
# import required module
import pandas as pd

In [2]:
# Create sample data, This dictionary mimics Toyota.csv structure
data = {
    'Price': [12000, 15000, 9000, 18000, 22000, 14000, 16000, 8000, 20000, 17000,
              11000, 13000, 21000, 9500, 15500, 14500, 16500, 18500, 12500, 17500, 25000, 35000],

    'Age': [5, 3, 12, 2, 1, 6, 4, 15, 2, 3,
            8, 7, 1, 14, 4, 6, 5, 2, 9, 3, 2, 4],

    'KM': [50000, 30000, 90000, 20000, 10000, 60000, 45000, 120000, 15000, 25000,
           70000, 65000, 8000, 110000, 48000, 58000, 52000, 22000, 75000, 27000, 10000, 20000],

    'FuelType': ['Petrol', 'Diesel', 'Petrol', 'Diesel', 'Hybrid',
                 'Petrol', 'Diesel', 'Petrol', 'Hybrid', 'Diesel',
                 'Petrol', 'Petrol', 'Hybrid', 'Diesel', 'Petrol',
                 'Diesel', 'Petrol', 'Hybrid', 'Diesel', 'Petrol', 'Electric', 'Electric'],

    'HP': [90, 110, 85, 120, 130, 95, 105, 80, 140, 115,
           92, 98, 135, 88, 108, 102, 100, 125, 96, 112, 100, 96],

    'Automatic': [0, 1, 0, 1, 1, 0, 1, 0, 1, 1,
                  0, 0, 1, 0, 1, 1, 0, 1, 0, 1, 0, 1],

    'Doors': [4, 4, 3, 4, 5, 4, 4, 3, 5, 4,
              4, 4, 5, 3, 4, 4, 4, 5, 4, 4, 4, 5],

    'Weight': [1100, 1200, 1050, 1300, 1400, 1150, 1250, 1000, 1450, 1350,
               1120, 1180, 1420, 1080, 1230, 1210, 1190, 1380, 1160, 1320, 1000, 1150]
}

In [3]:
# Converts raw data into a DataFrame

# .head() shows the first 5 rows for verification

df = pd.DataFrame(data)
df.head()

   Price  Age     KM FuelType   HP  Automatic  Doors  Weight
0  12000    5  50000   Petrol   90          0      4    1100
1  15000    3  30000   Diesel  110          1      4    1200
2   9000   12  90000   Petrol   85          0      3    1050
3  18000    2  20000   Diesel  120          1      4    1300
4  22000    1  10000   Hybrid  130          1      5    1400

In [4]:
# Number of rows and columns
df.shape

# Column names
df.columns

# Summary statistics for numeric columns
df.describe()

# Check for missing values
df.isnull().sum() #count missing data

Price        0
Age          0
KM           0
FuelType     0
HP           0
Automatic    0
Doors        0
Weight       0
dtype: int64

In [5]:
df.isnull().sum()

Price        0
Age          0
KM           0
FuelType     0
HP           0
Automatic    0
Doors        0
Weight       0
dtype: int64

Example 1: Selecting Columns by Exact Names:
Select only the Price, Age, and KM columns from the Toyota dataset.

In [6]:
df.filter(items=['Price', 'Age', 'KM'])

    Price  Age      KM
0   12000    5   50000
1   15000    3   30000
2    9000   12   90000
3   18000    2   20000
4   22000    1   10000
5   14000    6   60000
6   16000    4   45000
7    8000   15  120000
8   20000    2   15000
9   17000    3   25000
10  11000    8   70000
11  13000    7   65000
12  21000    1    8000
13   9500   14  110000
14  15500    4   48000
15  14500    6   58000
16  16500    5   52000
17  18500    2   22000
18  12500    9   75000
19  17500    3   27000
20  25000    2   10000
21  35000    4   20000

Selecting Columns Using like

-> Select all columns that contain the word "Type".

In [7]:
df.filter(like='Type')

# Returns all columns whose names include "Type"

# Useful when working with large datasets

    FuelType
0     Petrol
1     Diesel
2     Petrol
3     Diesel
4     Hybrid
5     Petrol
6     Diesel
7     Petrol
8     Hybrid
9     Diesel
10    Petrol
11    Petrol
12    Hybrid
13    Diesel
14    Petrol
15    Diesel
16    Petrol
17    Hybrid
18    Diesel
19    Petrol
20  Electric
21  Electric

Selecting Columns Using regex:
-> Select all columns that start with the letter A.

In [8]:
df.filter(regex='^A')
# ^ means “starts with”, Regex gives maximum flexibility

    Age  Automatic
0     5          0
1     3          1
2    12          0
3     2          1
4     1          1
5     6          0
6     4          1
7    15          0
8     2          1
9     3          1
10    8          0
11    7          0
12    1          1
13   14          0
14    4          1
15    6          1
16    5          0
17    2          1
18    9          0
19    3          1
20    2          0
21    4          1

In [9]:
print(df[df['Price'] > 15000])


'''df['Price'] > 15000 creates a Boolean Series (True / False). Pandas keeps only rows where the condition is True.
This is called Boolean Indexing.'''

    Price  Age     KM  FuelType   HP  Automatic  Doors  Weight
3   18000    2  20000    Diesel  120          1      4    1300
4   22000    1  10000    Hybrid  130          1      5    1400
6   16000    4  45000    Diesel  105          1      4    1250
8   20000    2  15000    Hybrid  140          1      5    1450
9   17000    3  25000    Diesel  115          1      4    1350
12  21000    1   8000    Hybrid  135          1      5    1420
14  15500    4  48000    Petrol  108          1      4    1230
16  16500    5  52000    Petrol  100          0      4    1190
17  18500    2  22000    Hybrid  125          1      5    1380
19  17500    3  27000    Petrol  112          1      4    1320
20  25000    2  10000  Electric  100          0      4    1000
21  35000    4  20000  Electric   96          1      5    1150

"df['Price'] > 15000 creates a Boolean Series (True / False). Pandas keeps only rows where the condition is True.\nThis is called Boolean Indexing."

loc accessor: The .loc[] method allows for more complex filtering, used to filter both rows and columns at the same time by specifying conditions for both axes. It allows to specify conditions directly within the square brackets.

In [10]:
df.loc[df['Price'] > 15000, ['Price', 'FuelType']]

# .loc[] is a label-based indexer. First part filters rows. Second part selects specific columns.

    Price  FuelType
3   18000    Diesel
4   22000    Hybrid
6   16000    Diesel
8   20000    Hybrid
9   17000    Diesel
12  21000    Hybrid
14  15500    Petrol
16  16500    Petrol
17  18500    Hybrid
19  17500    Petrol
20  25000  Electric
21  35000  Electric

Multi-Condition Filtering:
Each condition produces a Boolean Series.

& combines conditions element-wise.

Parentheses ensure correct order of evaluation.

Only rows where ALL conditions are true are returned.

Models real-world decision logic.

In [11]:
df[
    (df['FuelType'] == 'Petrol') &
    (df['Age'] > 10) &
    (df['Price'] < 10000)
]

   Price  Age      KM FuelType  HP  Automatic  Doors  Weight
2   9000   12   90000   Petrol  85          0      3    1050
7   8000   15  120000   Petrol  80          0      3    1000

Using .isin():

.isin() checks whether each value belongs to a given list.

Returns True if value is 3 OR 5.

Cleaner and safer than writing multiple OR conditions.

Used for category-based filtering.

In [12]:
df[df['Doors'].isin([3, 5])]

    Price  Age      KM  FuelType   HP  Automatic  Doors  Weight
2    9000   12   90000    Petrol   85          0      3    1050
4   22000    1   10000    Hybrid  130          1      5    1400
7    8000   15  120000    Petrol   80          0      3    1000
8   20000    2   15000    Hybrid  140          1      5    1450
12  21000    1    8000    Hybrid  135          1      5    1420
13   9500   14  110000    Diesel   88          0      3    1080
17  18500    2   22000    Hybrid  125          1      5    1380
21  35000    4   20000  Electric   96          1      5    1150

Grouping: Summarizing Data
The groupby() method allows you to group your data and execute functions on these groups.

# GroupBy + Single Aggregation
*  Split data by FuelType
*  Apply mean on Price
*   Combine results into one output

In [13]:
df.groupby('FuelType')['Price'].mean()

FuelType
Diesel      14642.857143
Electric    30000.000000
Hybrid      20375.000000
Petrol      12944.444444
Name: Price, dtype: float64

Multiple Metrics using .agg()

*   .agg() allows multiple calculations at once
*   Column renaming makes output readable
*   Used heavily in business reporting

In [16]:
df.groupby(['FuelType', 'Doors'])['Price'].mean()

FuelType  Doors
Diesel    3         9500.000000
          4        15500.000000
Electric  4        25000.000000
          5        35000.000000
Hybrid    5        20375.000000
Petrol    3         8500.000000
          4        14214.285714
Name: Price, dtype: float64